"""Auditable economic semantics for every category-metric formula."""

from __future__ import annotations

from typing import Final

FORMULA_PREFIX: Final = "upstream_audited_raw/"
FORMULA_SUFFIX: Final = "/0.1.0"
FORMULA_OWNER: Final = "upstream_audited_provider"


def _formula(name: str) -> str:
    return f"{FORMULA_PREFIX}{name}{FORMULA_SUFFIX}"


def _window(kind: str, unit: str, minimum: int, maximum: int) -> dict[str, object]:
    return {
        "kind": kind,
        "unit": unit,
        "minimum": minimum,
        "maximum": maximum,
    }


def _pit() -> dict[str, object]:
    return _window("point_in_time", "instant", 0, 0)


def _rolling(minimum: int = 12, maximum: int = 60) -> dict[str, object]:
    return _window("rolling_period", "months", minimum, maximum)


def _reporting(minimum: int = 1, maximum: int = 12) -> dict[str, object]:
    return _window("reporting_period", "months", minimum, maximum)


def _cumulative(minimum: int, maximum: int) -> dict[str, object]:
    return _window("cumulative_period", "months", minimum, maximum)


def _semantic(
    domain: str,
    unit: str,
    minimum: float,
    maximum: float,
    observation_window: dict[str, object],
    applicability: str,
    data_source: str,
) -> dict[str, object]:
    return {
        "domain": domain,
        "unit": unit,
        "value_range": {"minimum": minimum, "maximum": maximum},
        "observation_window": observation_window,
        "applicability": applicability,
        "formula_owner": FORMULA_OWNER,
        "data_source": data_source,
    }


# This is intentionally formula-by-formula rather than a name-token classifier.
# Every row is an independently reviewable economic contract.
FORMULA_SEMANTICS: Final[dict[str, dict[str, object]]] = {
    _formula("absolute_tracking_difference"): _semantic(
        "performance_return",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("allocation_effect"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("allocation_process_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("annualized_benchmark_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("asset_quality"): _semantic(
        "portfolio_exposure",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("asset_valuation_governance"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("below_investment_grade_exposure"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("benchmark_coverage"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "requires_declared_benchmark",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("benchmark_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("benchmark_excess_return"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("benchmark_return_gap"): _semantic(
        "performance_return",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("benchmark_yield_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("carry_efficiency"): _semantic(
        "performance_return",
        "ratio",
        0.0,
        1.0,
        _reporting(),
        "all_profile_funds",
        "income_distribution_and_market_data",
    ),
    _formula("carry_roll_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_derivative_or_commodity_exposure",
        "benchmark_and_market_series",
    ),
    _formula("collateral_quality"): _semantic(
        "portfolio_exposure",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_derivative_or_commodity_exposure",
        "custody_and_operations_records",
    ),
    _formula("concentration_deviation"): _semantic(
        "portfolio_exposure",
        "percentage_points",
        0.0,
        100.0,
        _pit(),
        "requires_declared_benchmark",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("concentration_hhi"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("contract_concentration"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "requires_derivative_or_commodity_exposure",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("country_weight_deviation"): _semantic(
        "portfolio_exposure",
        "percentage_points",
        0.0,
        100.0,
        _pit(),
        "requires_declared_benchmark",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("credit_concentration"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("credit_drawdown"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(12, 120),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("credit_event_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("credit_valuation_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("cross_border_custody_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_cross_border_or_currency_exposure",
        "custody_and_operations_records",
    ),
    _formula("cross_border_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_cross_border_or_currency_exposure",
        "regulatory_fund_disclosures",
    ),
    _formula("currency_adjusted_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "benchmark_and_market_series",
    ),
    _formula("currency_adjusted_tracking_gap"): _semantic(
        "performance_return",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "benchmark_and_market_series",
    ),
    _formula("currency_concentration"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "requires_cross_border_or_currency_exposure",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("currency_downside_capture"): _semantic(
        "downside_risk",
        "ratio",
        -5.0,
        5.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "benchmark_and_market_series",
    ),
    _formula("currency_stress_loss"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "benchmark_and_market_series",
    ),
    _formula("custody_or_collateral_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_derivative_or_commodity_exposure",
        "custody_and_operations_records",
    ),
    _formula("disclosure_timeliness"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _reporting(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("distribution_growth"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("distribution_stability"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("distribution_stress_loss"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("downside_capture"): _semantic(
        "downside_risk",
        "ratio",
        -5.0,
        5.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("duration_mandate_fit"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("expected_shortfall"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("factor_residual_alpha"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("futures_stress_loss"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(),
        "requires_derivative_or_commodity_exposure",
        "benchmark_and_market_series",
    ),
    _formula("fx_hedge_stability"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "fee_and_execution_records",
    ),
    _formula("fx_implementation_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        5000.0,
        _reporting(),
        "requires_cross_border_or_currency_exposure",
        "fee_and_execution_records",
    ),
    _formula("fx_tracking_error"): _semantic(
        "implementation_cost",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "benchmark_and_market_series",
    ),
    _formula("global_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_cross_border_or_currency_exposure",
        "fund_nav_and_market_series",
    ),
    _formula("high_quality_liquid_assets"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("index_method_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_declared_benchmark",
        "regulatory_fund_disclosures",
    ),
    _formula("lifecycle_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("liquidity_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        5000.0,
        _reporting(),
        "all_profile_funds",
        "fee_and_execution_records",
    ),
    _formula("liquidity_governance_quality"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("liquidity_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("liquidity_stress_loss"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("lookthrough_concentration"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "requires_lookthrough_portfolio",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("lookthrough_total_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        2000.0,
        _reporting(12, 12),
        "requires_lookthrough_portfolio",
        "fee_and_execution_records",
    ),
    _formula("mandate_active_share"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "requires_declared_benchmark",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("mandate_country_fit"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "requires_cross_border_or_currency_exposure",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("market_liquidity_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        5000.0,
        _reporting(),
        "all_profile_funds",
        "fee_and_execution_records",
    ),
    _formula("maximum_drawdown"): _semantic(
        "downside_risk",
        "percent",
        0.0,
        100.0,
        _rolling(12, 120),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("negative_return_days"): _semantic(
        "downside_risk",
        "count",
        0.0,
        366.0,
        _rolling(1, 12),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("occupancy_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("ongoing_charge"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        1000.0,
        _reporting(12, 12),
        "all_profile_funds",
        "fee_and_execution_records",
    ),
    _formula("policy_benchmark_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("rate_credit_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("rate_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("recovery_months"): _semantic(
        "downside_risk",
        "months",
        0.0,
        1200.0,
        _cumulative(0, 1200),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("redemption_liquidity_buffer"): _semantic(
        "implementation_cost",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("related_party_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("replication_method_stability"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_declared_benchmark",
        "regulatory_fund_disclosures",
    ),
    _formula("roll_implementation_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        5000.0,
        _reporting(),
        "requires_derivative_or_commodity_exposure",
        "fee_and_execution_records",
    ),
    _formula("roll_regime_persistence"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_derivative_or_commodity_exposure",
        "benchmark_and_market_series",
    ),
    _formula("roll_yield_efficiency"): _semantic(
        "performance_return",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_derivative_or_commodity_exposure",
        "benchmark_and_market_series",
    ),
    _formula("rolling_excess_hit_rate"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("rolling_goal_hit_rate"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "all_profile_funds",
        "fund_nav_and_market_series",
    ),
    _formula("rolling_positive_excess"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("rolling_tracking_stability"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("rolling_yield_rank_stability"): _semantic(
        "consistency_stability",
        "ratio",
        0.0,
        1.0,
        _rolling(),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("securities_lending_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_securities_lending_program",
        "custody_and_operations_records",
    ),
    _formula("settlement_delay"): _semantic(
        "implementation_cost",
        "days",
        0.0,
        365.0,
        _reporting(),
        "all_profile_funds",
        "custody_and_operations_records",
    ),
    _formula("seven_day_yield_stability"): _semantic(
        "performance_return",
        "ratio",
        0.0,
        1.0,
        _rolling(1, 12),
        "requires_income_distributing_assets",
        "income_distribution_and_market_data",
    ),
    _formula("shadow_nav_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("spot_tracking_gap"): _semantic(
        "performance_return",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_derivative_or_commodity_exposure",
        "benchmark_and_market_series",
    ),
    _formula("tenant_concentration"): _semantic(
        "portfolio_exposure",
        "percent",
        0.0,
        100.0,
        _pit(),
        "requires_income_distributing_assets",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("total_expense"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        1000.0,
        _reporting(12, 12),
        "all_profile_funds",
        "fee_and_execution_records",
    ),
    _formula("total_return_excess"): _semantic(
        "performance_return",
        "percentage_points",
        -100.0,
        1000.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("tracking_error"): _semantic(
        "implementation_cost",
        "percentage_points",
        0.0,
        100.0,
        _rolling(),
        "requires_declared_benchmark",
        "benchmark_and_market_series",
    ),
    _formula("underlying_diversification"): _semantic(
        "portfolio_exposure",
        "ratio",
        0.0,
        1.0,
        _pit(),
        "requires_lookthrough_portfolio",
        "portfolio_holdings_and_lookthrough",
    ),
    _formula("underlying_due_diligence"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "requires_lookthrough_portfolio",
        "regulatory_fund_disclosures",
    ),
    _formula("underlying_liquidity_cost"): _semantic(
        "implementation_cost",
        "basis_points",
        0.0,
        5000.0,
        _reporting(),
        "requires_lookthrough_portfolio",
        "fee_and_execution_records",
    ),
    _formula("valuation_control_quality"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("valuation_cutoff_controls"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("valuation_method_disclosure"): _semantic(
        "governance_control",
        "score_0_100",
        0.0,
        100.0,
        _pit(),
        "all_profile_funds",
        "regulatory_fund_disclosures",
    ),
    _formula("weighted_average_maturity"): _semantic(
        "portfolio_exposure",
        "days",
        0.0,
        180.0,
        _pit(),
        "all_profile_funds",
        "portfolio_holdings_and_lookthrough",
    ),
}

SEMANTIC_FIELDS: Final = frozenset(
    {
        "domain",
        "unit",
        "value_range",
        "observation_window",
        "applicability",
        "formula_owner",
        "data_source",
    }
)
UNITS: Final = frozenset(
    {
        "basis_points",
        "count",
        "days",
        "months",
        "percent",
        "percentage_points",
        "ratio",
        "score_0_100",
    }
)
WINDOW_KINDS: Final = frozenset(
    {"cumulative_period", "point_in_time", "reporting_period", "rolling_period"}
)
WINDOW_UNITS: Final = frozenset({"instant", "months"})
APPLICABILITY: Final = frozenset(
    {
        "all_profile_funds",
        "requires_cross_border_or_currency_exposure",
        "requires_declared_benchmark",
        "requires_derivative_or_commodity_exposure",
        "requires_income_distributing_assets",
        "requires_lookthrough_portfolio",
        "requires_securities_lending_program",
    }
)
DATA_SOURCES: Final = frozenset(
    {
        "benchmark_and_market_series",
        "custody_and_operations_records",
        "fee_and_execution_records",
        "fund_nav_and_market_series",
        "income_distribution_and_market_data",
        "portfolio_holdings_and_lookthrough",
        "regulatory_fund_disclosures",
    }
)
